# To keep the application alive
camel.springboot.main-run-controller: true

# File directories
file.in.dir: ${user.home}/camel-spring-boot-demo/in
file.out.dir: ${user.home}/camel-spring-boot-demo/out